global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dev'
    environment: 'exam07'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'sre-demo'
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'sre-demo'
    
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
