apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-demo-prod

resources:
  - ../../app
  - hpa.yaml

images:
  - name: ghcr.io/example/gitops-demo
    newTag: stable

replicas:
  - name: gitops-demo
    count: 3

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: gitops-demo-env-config
    literals:
      - LOG_LEVEL=info
      - ENVIRONMENT=production
