apiVersion: v1
kind: Service
metadata:
  name: observability-slo
  labels:
    app: observability-slo
spec:
  selector:
    app: observability-slo
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
