apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo

commonLabels:
  app.kubernetes.io/name: devops-demo
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - hpa.yaml
  - pdb.yaml

configMapGenerator:
  - name: devops-demo-config
    literals:
      - SERVICE_NAME=devops-demo
      - LOG_LEVEL=INFO
