apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-demo

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - pdb.yaml

configMapGenerator:
  - name: gitops-demo-config
    literals:
      - APP_NAME=gitops-demo
      - LOG_FORMAT=json
