apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  labels:
    app: gitops-demo
spec:
  selector:
    app: gitops-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
