apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo-stable
  labels:
    app: canary-demo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-demo
      track: stable
  template:
    metadata:
      labels:
        app: canary-demo
        track: stable
        version: v1
    spec:
      containers:
      - name: app
        image: local/canary-demo:v1
        ports:
        - name: http
          containerPort: 8000
