apiVersion: v1
kind: Service
metadata:
  name: hardened-app
  labels:
    app: hardened-app
spec:
  type: ClusterIP
  selector:
    app: hardened-app
  ports:
  - name: http
    port: 80
    targetPort: http
