apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-demo-dev

resources:
  - ../../app

images:
  - name: ghcr.io/example/gitops-demo
    newTag: dev

replicas:
  - name: gitops-demo
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: gitops-demo-env-config
    literals:
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
